name: "Run ARM-TTK with reviewdog"
description: "🐶 Run ARM-TTK with reviewdog on pull requests to improve code review experience."
author: "dciborow"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    required: true
    default: "${{ github.token }}"
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  glob_pattern:
    description: "Glob pattern of the files to lint"
    required: false
    default: "."
  ### Flags for reviewdog ###
  tool_name:
    description: "Tool name to use for reviewdog reporter."
    required: false
    default: "armttk"
  level:
    description: "Report level for reviewdog [info,warning,error]"
    required: false
    default: "error"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check,github-pr-review]."
    required: false
    default: "github-pr-check"
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    required: false
    default: "added"
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    required: false
    default: "false"
  reviewdog_flags:
    description: "Additional reviewdog flags"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run ARM-TTK
      shell: pwsh
      run: |
        Install-Module -Name Pester -RequiredVersion 4.10.1 -Force
        Import-Module -Name Pester -RequiredVersion 4.10.1 -Force
        Invoke-WebRequest -Uri aka.ms/arm-ttk-latest -OutFile arm-template-toolkit.zip
        Expand-Archive -LiteralPath arm-template-toolkit.zip -DestinationPath arm-ttk
        Import-Module ./arm-ttk/arm-ttk/arm-ttk.psd1
        echo "Test-AzTemplate -TemplatePath ${{ inputs.templatesFolderPath }} -Pester -Skip Secure-Params-In-Nested-Deployments" | Out-File -FilePath ./armttk.ps1
        Invoke-Pester -Script ./armttk.ps1 -EnableExit -OutputFormat NUnitXml -OutputFile ./armttk.xml
    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: ARMTTKResults
        path: ./armttk.xml
      if: ${{ always() }}
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_GLOB_PATTERN: ${{ inputs.glob_pattern }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "check"
  color: "blue"
